[package]
name = "basel"
version = "0.0.0"
edition = "2021"

[dependencies]
geojson = "0.24.1"
reqwest = "0.12.8"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
time = { version = "0.3.36", features = ["serde", "formatting", "parsing"] }
